In [180]:
import numpy as np
np.random.seed(42)


class sample(object):
    def __init__(self, X, n_subspace):
        self.idx_subspace = self.random_subspace(X, n_subspace)

    def __call__(self, X, y):
        idx_obj = self.bootstrap_sample(X)
        X_sampled, y_sampled = self.get_subsample(X, y, self.idx_subspace, idx_obj)

        return X_sampled, y_sampled

    @staticmethod
    def bootstrap_sample(X, random_state=42):
        """
        Заполните тело этой функции таким образом, чтобы она возвращала массив индексов выбранных при помощи бэггинга индексов.
        Пользуйтесь только инструментами, реализованными в numpy.random, выставляя везде, где это необходимо, random_state=42
        """
        n, d = X.shape

        #return np.random.choice(a=np.arange(n), size=n, replace=False)
        res = np.random.choice(a=np.arange(n), size=n)

        return np.unique(res)

    @staticmethod
    def random_subspace(X, n_subspace, random_state=42):
        """
        Заполните тело этой функции таким образом, чтобы она возвращала массив индексов выбранных при помощи метода случайных подпространств признаков
        Количество этих признаков передается при помощи аргумента n_subspace
        Пользуйтесь только инструментами, реализованными в numpy.random, выставляя везде, где это необходимо, random_state=42
        """
        n, d = X.shape

        #return np.random.choice(a=np.arange(d), size=n_subspace, replace=False)
        res = np.random.choice(a=np.arange(d), size=n_subspace)

        return res

    @staticmethod
    def get_subsample(X, y, idx_subspace, idx_obj):
        """
        Заполните тело этой функции таким образом, чтобы она возвращала подвыборку x_sampled, y_sampled
        по значениям индексов признаков(idx_subspace) и объектов(idx_obj), которые должны в неё попасть
        """
        X_sampled = np.take(a=X, indices=idx_obj, axis=0)
        y_sampled = np.take(a=y, indices=idx_obj, axis=0)

        X_sampled = np.take(a=X_sampled, indices=idx_subspace, axis=1)

        return X_sampled, y_sampled

In [181]:
X = np.array([[1,2,3], [4,5,6], [7,8,9]])
Y = np.array([1, 2, 3])
s = sample(X, 2)

bootstrap_indices = s.bootstrap_sample(X)
X_sampled, y_sampled = s.get_subsample(X, Y, s.idx_subspace, bootstrap_indices)

In [182]:
# Строки, выбранные из исходного массива X
bootstrap_indices

array([0, 2])

In [183]:
# Столбцы, выбранные из исходного массива X
s.idx_subspace

array([2, 0])

In [184]:
# Матрица на выходе
X_sampled

array([[3, 1],
       [9, 7]])

In [185]:
# Вектор ответов на выходе
y_sampled

array([1, 3])